const app = document.querySelector('#app');
const favoriteCount = document.querySelector('#favorite-count');
const menuToggle = document.querySelector('#menu-toggle');
const nav = document.querySelector('.main-nav');
const STORAGE_KEY = 'el-pulso-favoritos';
const CUSTOM_NEWS_KEY = 'el-pulso-noticias';
const DELETED_NEWS_KEY = 'el-pulso-noticias-eliminadas';

let news = [];
let favorites = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');

const formatDate = (date) => new Intl.DateTimeFormat('es-CO', { dateStyle: 'long' }).format(new Date(`${date}T12:00:00`));
const getFavorites = () => news.filter((item) => favorites.includes(item.id));
const saveFavorites = () => { localStorage.setItem(STORAGE_KEY, JSON.stringify(favorites)); updateFavoriteCount(); };
const updateFavoriteCount = () => { favoriteCount.textContent = favorites.length; };
const cardTemplate = (item) => `<article class="news-card"><a class="card-image" href="#noticia/${item.id}"><img src="${item.image}" alt="${item.imageAlt}" loading="lazy"></a><div class="card-body"><div class="card-meta"><span>${item.category}</span><time datetime="${item.date}">${formatDate(item.date)}</time></div><h3><a href="#noticia/${item.id}">${item.title}</a></h3><p>${item.excerpt}</p><div class="card-footer"><a class="read-link" href="#noticia/${item.id}">Leer más <span aria-hidden="true">→</span></a><button class="favorite-button ${favorites.includes(item.id) ? 'is-favorite' : ''}" data-favorite="${item.id}" type="button" aria-label="${favorites.includes(item.id) ? 'Quitar de favoritos' : 'Agregar a favoritos'}">${favorites.includes(item.id) ? '★' : '☆'}</button></div></div></article>`;
const cardsTemplate = (items) => items.length ? `<div class="news-grid">${items.map(cardTemplate).join('')}</div>` : '<div class="empty-state"><span class="empty-icon">☆</span><h2>Aún no tienes favoritos</h2><p>Guarda las historias que quieras leer con más calma y aparecerán aquí.</p><a class="button button-dark" href="#noticias">Explorar noticias</a></div>';

function renderHome() {
  const [lead, ...rest] = news;
  app.innerHTML = `<section class="hero"><div class="hero-copy"><p class="kicker">Edición de septiembre · 2026</p><h1>Historias para mirar <em>más allá</em> del titular.</h1><p class="hero-description">El Pulso reúne periodismo de contexto, voces diversas y las preguntas que importan para entender nuestro presente.</p><div class="hero-actions"><a class="button button-accent" href="#noticias">Explorar noticias <span>→</span></a><a class="text-button" href="#contacto">Escríbenos</a></div></div><div class="hero-note"><span class="note-line"></span><p>Una plataforma de noticias<br>para una lectura más consciente.</p></div></section><section class="section-block featured-section"><div class="section-heading"><div><p class="kicker">Selección editorial</p><h2>Historias destacadas</h2></div><a class="read-link" href="#noticias">Ver todas <span>→</span></a></div><div class="featured-grid"><article class="featured-lead"><a class="featured-image" href="#noticia/${lead.id}"><img src="${lead.image}" alt="${lead.imageAlt}"></a><div class="featured-copy"><div class="card-meta"><span>${lead.category}</span><time datetime="${lead.date}">${formatDate(lead.date)}</time></div><h3><a href="#noticia/${lead.id}">${lead.title}</a></h3><p>${lead.excerpt}</p><a class="read-link" href="#noticia/${lead.id}">Leer la historia <span>→</span></a></div></article><div class="side-stories">${rest.slice(0, 2).map(cardTemplate).join('')}</div></div></section>`;
}

function renderCatalog() {
  app.innerHTML = `<section class="page-heading"><p class="kicker">Archivo editorial</p><h1>Todas las noticias</h1><p>Una mirada cercana a las transformaciones que están ocurriendo a nuestro alrededor.</p></section><section class="section-block catalog-block"><div class="catalog-toolbar"><span>${news.length} historias disponibles</span><label>Filtrar por <select id="category-filter"><option value="Todas">Todas las categorías</option>${[...new Set(news.map((item) => item.category))].map((category) => `<option>${category}</option>`).join('')}</select></label></div><div id="catalog-results">${cardsTemplate(news)}</div></section>`;
  document.querySelector('#category-filter').addEventListener('change', (event) => { document.querySelector('#catalog-results').innerHTML = cardsTemplate(event.target.value === 'Todas' ? news : news.filter((item) => item.category === event.target.value)); });
}

function renderDetail(id) {
  const item = news.find((entry) => entry.id === id);
  if (!item) { renderNotFound(); return; }
  app.innerHTML = `<article class="article-detail"><a class="back-link" href="#noticias">← Volver a noticias</a><div class="article-header"><div class="card-meta"><span>${item.category}</span><time datetime="${item.date}">${formatDate(item.date)}</time></div><h1>${item.title}</h1><p class="article-deck">${item.excerpt}</p><div class="article-byline"><span class="author-avatar">${item.author.charAt(0)}</span><span>Por <strong>${item.author}</strong></span><button class="favorite-button detail-favorite ${favorites.includes(item.id) ? 'is-favorite' : ''}" data-favorite="${item.id}" type="button">${favorites.includes(item.id) ? '★ Guardada' : '☆ Guardar'}</button></div></div><img class="article-image" src="${item.image}" alt="${item.imageAlt}"><div class="article-content">${item.content.split('\n\n').map((paragraph) => `<p>${paragraph}</p>`).join('')}</div></article>`;
}

function renderFavorites() { app.innerHTML = `<section class="page-heading"><p class="kicker">Tu selección</p><h1>Noticias favoritas</h1><p>Historias guardadas para volver a ellas cuando tengas tiempo.</p></section><section class="section-block">${cardsTemplate(getFavorites())}</section>`; }
function renderContact() { app.innerHTML = `<section class="page-heading"><p class="kicker">Hablemos</p><h1>Contacto</h1><p>¿Tienes una historia, una pregunta o un comentario? Este canal es una demostración local.</p></section><section class="contact-layout"><div class="contact-aside"><span class="aside-number">01</span><h2>Tu voz también hace parte de la conversación.</h2><p>El formulario no envía información a un servidor. La confirmación que aparece es únicamente local.</p></div><form class="contact-form" id="contact-form" novalidate><label>Nombre<input name="name" required autocomplete="name" placeholder="Tu nombre"><small class="error-message"></small></label><label>Correo electrónico<input name="email" type="email" required autocomplete="email" placeholder="nombre@correo.com"><small class="error-message"></small></label><label>Asunto<input name="subject" required placeholder="¿Sobre qué quieres escribir?"><small class="error-message"></small></label><label>Mensaje<textarea name="message" required rows="5" placeholder="Cuéntanos..."></textarea><small class="error-message"></small></label><button class="button button-dark" type="submit">Enviar mensaje <span>→</span></button><p class="form-status" role="status"></p></form></section>`; document.querySelector('#contact-form').addEventListener('submit', handleContact); }
function renderAdmin() { app.innerHTML = `<section class="page-heading"><p class="kicker">Herramientas locales</p><h1>Administrar noticias</h1><p>Crea contenido de muestra o elimina noticias. Los cambios quedan guardados solo en este navegador.</p></section><section class="admin-layout"><form class="admin-form" id="news-form"><h2>Crear una noticia</h2><label>Título<input name="title" required></label><label>Categoría<input name="category" required placeholder="Ej. Tecnología"></label><label>Descripción breve<textarea name="excerpt" required rows="3"></textarea></label><label>Contenido completo<textarea name="content" required rows="5"></textarea></label><label>Autor<input name="author" required></label><label>Imagen (URL)<input name="image" type="url" required placeholder="https://..."></label><button class="button button-accent" type="submit">Publicar noticia <span>→</span></button><p class="form-status" role="status"></p></form><div class="admin-list"><h2>Noticias disponibles <span>${news.length}</span></h2>${news.map((item) => `<div class="admin-item"><div><strong>${item.title}</strong><small>${item.category}</small></div><button class="delete-button" data-delete="${item.id}" type="button">Eliminar</button></div>`).join('')}</div></section>`; document.querySelector('#news-form').addEventListener('submit', handleCreate); }
function renderNotFound() { app.innerHTML = '<section class="empty-state"><span class="empty-icon">?</span><h2>Esta historia no existe</h2><p>Puede que haya sido eliminada de la edición local.</p><a class="button button-dark" href="#noticias">Volver al catálogo</a></section>'; }

function handleContact(event) { event.preventDefault(); const form = event.target; let valid = true; form.querySelectorAll('label').forEach((label) => { const input = label.querySelector('input, textarea'); const error = label.querySelector('.error-message'); error.textContent = ''; label.classList.remove('has-error'); if (!input.value.trim()) { error.textContent = 'Este campo es obligatorio.'; label.classList.add('has-error'); valid = false; } else if (input.type === 'email' && !input.validity.valid) { error.textContent = 'Escribe un correo válido.'; label.classList.add('has-error'); valid = false; } }); const status = form.querySelector('.form-status'); status.textContent = valid ? 'Mensaje validado. Esta es una demostración local; no se realizó ningún envío.' : ''; status.className = `form-status ${valid ? 'success-message' : ''}`; if (valid) form.reset(); }
function handleCreate(event) { event.preventDefault(); const form = event.target; const data = Object.fromEntries(new FormData(form)); const status = form.querySelector('.form-status'); const item = { ...data, id: `${data.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${Date.now()}`, date: new Date().toISOString().slice(0, 10), imageAlt: data.title }; const custom = JSON.parse(localStorage.getItem(CUSTOM_NEWS_KEY) || '[]'); custom.push(item); localStorage.setItem(CUSTOM_NEWS_KEY, JSON.stringify(custom)); news.push(item); status.textContent = 'Noticia creada y guardada localmente.'; status.className = 'form-status success-message'; form.reset(); setTimeout(renderAdmin, 700); }
function deleteNews(id) { const baseIds = ['ciudades-que-respiran', 'ciencia-del-sueno', 'cocinas-del-pacifico', 'energia-del-viento']; news = news.filter((item) => item.id !== id); if (baseIds.includes(id)) { const deleted = JSON.parse(localStorage.getItem(DELETED_NEWS_KEY) || '[]'); localStorage.setItem(DELETED_NEWS_KEY, JSON.stringify([...new Set([...deleted, id])])); } const custom = JSON.parse(localStorage.getItem(CUSTOM_NEWS_KEY) || '[]'); localStorage.setItem(CUSTOM_NEWS_KEY, JSON.stringify(custom.filter((item) => item.id !== id))); renderAdmin(); }

function route() { const hash = location.hash.slice(1) || 'inicio'; const [page, id] = hash.split('/'); document.querySelectorAll('[data-route]').forEach((link) => link.classList.toggle('active', link.dataset.route === page || (page === 'noticia' && link.dataset.route === 'noticias'))); if (page === 'inicio') renderHome(); else if (page === 'noticias') renderCatalog(); else if (page === 'noticia') renderDetail(id); else if (page === 'favoritos') renderFavorites(); else if (page === 'contacto') renderContact(); else if (page === 'admin') renderAdmin(); else renderNotFound(); updateFavoriteCount(); app.focus(); nav.classList.remove('is-open'); menuToggle.setAttribute('aria-expanded', 'false'); }

document.addEventListener('click', (event) => { const button = event.target.closest('[data-favorite]'); if (button) { const id = button.dataset.favorite; favorites = favorites.includes(id) ? favorites.filter((favorite) => favorite !== id) : [...favorites, id]; saveFavorites(); route(); } const deleteButton = event.target.closest('[data-delete]'); if (deleteButton) deleteNews(deleteButton.dataset.delete); });
menuToggle.addEventListener('click', () => { const isOpen = nav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', isOpen); });
window.addEventListener('hashchange', route);

async function init() { try { const response = await fetch('data/news.json'); if (!response.ok) throw new Error('No se pudo cargar el catálogo'); const baseNews = await response.json(); const deleted = JSON.parse(localStorage.getItem(DELETED_NEWS_KEY) || '[]'); const custom = JSON.parse(localStorage.getItem(CUSTOM_NEWS_KEY) || '[]'); news = [...baseNews.filter((item) => !deleted.includes(item.id)), ...custom]; route(); } catch (error) { app.innerHTML = '<section class="empty-state"><h2>No se pudo cargar la edición</h2><p>Ejecuta el proyecto mediante un servidor local para cargar el archivo JSON.</p></section>'; } }
init();